from enum import Enum

class ResponseCode(str, Enum):
    CREATED = "CREATED"

    ALREADY_REGISTERED = "ALREADY_REGISTERED"

    MATCH_FOUND = "MATCH_FOUND"
    NO_MATCH = "NO_MATCH"

    INVALID_IMAGE = "INVALID_IMAGE"
    NO_FACE = "NO_FACE"
    MULTIPLE_FACES = "MULTIPLE_FACES"
    FACE_TOO_SMALL = "FACE_TOO_SMALL"

    DUPLICATE_FACE = "DUPLICATE_FACE"

    TEMPORARY_ERROR = "TEMPORARY_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"